POST http://localhost:3000/auth/login
Content-Type: application/json

# {
#   "firstName": "fake",
#   "lastName": "person",
#   "email": "fakePerson@gmail.com",
#   "password": "pass123",
#   "occupation": "fakeOccupation"
# }

{
  "email": "fakePerson@gmail.com",
  "password": "pass123"
}